test report failed result parser

diff --git a/tools/pipelines/test-azure-frs.yml b/tools/pipelines/test-azure-frs.yml
--- a/tools/pipelines/test-azure-frs.yml
+++ b/tools/pipelines/test-azure-frs.yml
@@ -5,6 +5,88 @@
 
 name: $(Build.BuildId)
 
+parameters:
+- name: buildDirectory
+  type: string
+
+- name: taskBuild
+  type: string
+  default: ci:build
+
+- name: taskBuildDocs
+  type: boolean
+  default: true
+
+- name: taskLint
+  type: boolean
+  default: true
+
+- name: taskTest
+  type: object
+  default:
+  - ci:test
+
+- name: taskBundleAnalysis
+  type: boolean
+  default: false
+
+- name: taskPublishBundleSizeArtifacts
+  type: boolean
+  default: false
+
+- name: taskPack
+  type: boolean
+  default: true
+
+- name: poolCG
+  type: object
+  default: Small
+
+- name: poolBuild
+  type: object
+  default: Small
+
+- name: preCG
+  type: stepList
+  default: []
+
+- name: cgSubDirectory
+  type: string
+  default:
+
+- name: checkoutSubmodules
+  type: boolean
+  default: false
+
+- name: namespace
+  type: boolean
+  default: true
+
+- name: buildNumberInPatch
+  type: string
+  default:
+
+- name: nonScopedPackages
+  type: object
+  default: []
+
+- name: publishOverride
+  type: string
+
+- name: releaseBuildOverride
+  type: string
+
+- name: tagName
+  type: string
+
+- name: includeInternalVersions
+  type: boolean
+  default: false
+
+- name: buildToolsVersionToInstall
+  type: string
+  default: repo
+
 trigger:
   branches:
     include:
@@ -42,37 +124,224 @@ variables:
 - group: prague-key-vault
 - name: testWorkspace
   value: $(Pipeline.Workspace)/test
+  parameters:
+    publishOverride: ${{ parameters.publishOverride }}
+    releaseBuildOverride: ${{ parameters.releaseBuildOverride }}
+    buildNumberInPatch: ${{ parameters.buildNumberInPatch }}
+    nonScopedPackages: ${{ parameters.nonScopedPackages }}
 
 stages:
-  # Run Azure Client FRS Tests
-  - stage:
-    displayName: e2e - azure client with frs
-    dependsOn: []
+    # Install / Build / Test Stage
+  - stage: build
+    displayName: Build Stage
     jobs:
-    - template: templates/include-test-real-service.yml
-      parameters:
-        poolBuild: Small
-        testPackage: "@fluidframework/azure-end-to-end-tests"
-        testWorkspace: ${{ variables.testWorkspace }}
-        testCommand: test:realsvc:azure
-        extraDependencies: "cross-env mocha @fluidframework/test-client-utils"
-        downloadAzureTestArtifacts: true
-        env:
-          FLUID_TEST_LOGGER_PKG_PATH: ${{ variables.testWorkspace }}/node_modules/@ff-internal/aria-logger # Contains getTestLogger impl to inject
-          azure__fluid__relay__service__tenantId: $(azure-fluid-relay-service-tenantId)
-          azure__fluid__relay__service__function__url: $(azure-fluid-relay-service-function-url)
+      # Job - Build
+      - job: build
+        displayName: Build
+        pool: ${{ parameters.poolBuild }}
+        variables:
+          testCoverage: ${{ ne(variables['Build.Reason'], 'PullRequest') }}
+          releaseBuildVar: $[variables.releaseBuild]
+          ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
+            targetBranchName: $(System.PullRequest.TargetBranch)
+        steps:
+        # Setup
+        - checkout: self
+          clean: true
+          lfs: ${{ parameters.checkoutSubmodules }}
+          submodules: ${{ parameters.checkoutSubmodules }}
 
-  - stage:
-    displayName: e2e - azure client with azure local service
-    dependsOn: []
-    jobs:
-    - template: templates/include-test-real-service.yml
+        - task: Bash@3
+          displayName: Parameters
+          inputs:
+            targetType: 'inline'
+            workingDirectory: ${{ parameters.buildDirectory }}
+            script: |
+              # Show all task group conditions
+
+              echo "
+              Pipeline Variables:
+                releaseBuild=$(releaseBuildVar)
+
+              Override Parameters:
+                publishOverride=${{ parameters.publishOverride }}
+                releaseBuildOverride=${{ parameters.releaseBuildOverride }}
+
+              Tasks Parameters:
+                BuildDir=${{ parameters.buildDirectory }}
+                Build=${{ parameters.taskBuild }}
+                Lint=${{ parameters.taskLint }}
+                Test=${{ convertToJson(parameters.taskTest) }}
+                BuildDoc=${{ parameters.taskBuildDocs }}
+                TestCoverage=$(testCoverage)
+
+              Publish Parameters:
+                nonScopedPackages=${{ join(', ', parameters.nonScopedPackages) }}
+
+              Computed variables:
+                shouldPublish=${{ variables.shouldPublish }}
+                componentDetection=${{ variables.componentDetection }}
+                publish=${{ variables.publish }}
+                canRelease=${{ variables.canRelease }}
+                publishNonScopedPackages=${{ variables.publishNonScopedPackages }}
+
+                release=$(release)"
+
+              # Target Branch variable (PR policy related)
+              if [[ ${{ variables['Build.Reason'] }} == "PullRequest" ]]; then
+                echo "TargetBranchName=$(targetBranchName)"
+              fi
+
+              # Error checking
+              if [[ "$(release)" == "release" ]]; then
+                if [[ "${{ variables.canRelease }}" == "False" ]]; then
+                  echo "##vso[task.logissue type=error]Invalid branch ${{ variables['Build.SourceBranch'] }} for release"
+                  exit -1;
+                fi
+
+                if [ -f "lerna.json" ]; then
+                  grep -e fluid.*[0-9]-[0-9] `find packages -name 'package.json'`
+                else
+                  grep -e fluid.*[0-9]-[0-9] `find . -name 'package.json'`
+                fi
+
+                if [[ $? == 0 ]]; then
+                  echo "##vso[task.logissue type=error]Release shouldn't contain prerelease dependencies"
+                  exit -1;
+                fi
+              fi
+
+              if [[ "$(release)" == "prerelease" ]]; then
+                if [[ "${{ parameters.buildNumberInPatch }}" == "true" ]]; then
+                  echo "##vso[task.logissue type=error] Prerelease not allow for builds that put build number as the patch version"
+                  exit -1;
+                fi
+              fi
+
+              if [[ "$(release)" != "none" ]] && [[ "$(release)" != "" ]]; then
+                if [[ "${{ variables.publish }}" != "True" ]]; then
+                  echo "##vso[task.logissue type=error]'$(release)'' is set but package is not published. Either the branch doesn't default to publish or it is skipped."
+                  exit -1;
+                fi
+              fi
+
+        # Install
+        - task: UseNode@1
+          displayName: Use Node 14.x
+          inputs:
+            version: 14.x
+        - task: Npm@1
+          displayName: npm ci
+          inputs:
+            command: 'custom'
+            workingDir: ${{ parameters.buildDirectory }}
+            customCommand: 'ci --unsafe-perm'
+            customRegistry: 'useNpmrc'
+
+        # Set version
+        - template: include-set-package-version.yml
+          parameters:
+            buildDirectory: ${{ parameters.buildDirectory }}
+            buildNumberInPatch: ${{ parameters.buildNumberInPatch }}
+            buildToolsVersionToInstall: ${{ parameters.buildToolsVersionToInstall }}
+            tagName: ${{ parameters.tagName }}
+
+        # Build
+        - ${{ if ne(parameters.taskBuild, 'false') }}:
+          - task: Npm@1
+            displayName: npm run ${{ parameters.taskBuild }}
+            inputs:
+              command: 'custom'
+              workingDir: ${{ parameters.buildDirectory }}
+              customCommand: 'run ${{ parameters.taskBuild }}'
+
+        # Lint
+        - ${{ if ne(parameters.taskLint, false) }}:
+          - task: Npm@1
+            displayName: npm run lint
+            inputs:
+              command: 'custom'
+              workingDir: ${{ parameters.buildDirectory }}
+              customCommand: 'run lint'
+
+        # Test
+        - ${{ if ne(convertToJson(parameters.taskTest), '[]') }}:
+          # Set variable startTest if the build succeed so that we can run all the test tasks whether they are failed or not
+          - script: |
+              echo "##vso[task.setvariable variable=startTest]true"
+            displayName: Start Test
+
+          - ${{ each taskTestStep in parameters.taskTest }}:
+            # Test - With coverage
+            - ${{ if and(eq(variables['testCoverage'], true), startsWith(taskTestStep, 'ci:test')) }}:
+              - task: Npm@1
+                displayName: npm run ${{ taskTestStep }}:coverage
+                inputs:
+                  command: 'custom'
+                  workingDir: ${{ parameters.buildDirectory }}
+                  customCommand: 'run ${{ taskTestStep }}:coverage'
+                condition: and(succeededOrFailed(), eq(variables['startTest'], 'true'))
+            # Test - No coverage
+            - ${{ if or(eq(variables['testCoverage'], false), eq(startsWith(taskTestStep, 'ci:test'), false)) }}:
+                - task: Npm@1
+                  displayName: npm run ${{ taskTestStep }}
+                  inputs:
+                    command: 'custom'
+                    workingDir: ${{ parameters.buildDirectory }}
+                    customCommand: 'run ${{ taskTestStep }}'
+                  condition: and(succeededOrFailed(), eq(variables['startTest'], 'true'))
+
+          # Test - Upload coverage results
+          # Some webpacked file using externals introduce file name with quotes in them
+          # and Istanbul's cobertura reporter doesn't escape them causing parse error when we publish
+          # A quick fix to patch the file with sed. (See https://github.com/bcoe/c8/issues/302)
+          - ${{ if eq(variables['testCoverage'], true) }}:
+            - task: Bash@3
+              displayName: 'Check for nyc/report directory'
+              inputs:
+                targetType: 'inline'
+                workingDirectory: ${{ parameters.buildDirectory }}
+                script: |
+                  test -d nyc/report && echo '##vso[task.setvariable variable=ReportDirExists;]true' || echo 'No nyc/report directory'
+              condition: and(succeededOrFailed(), eq(variables['startTest'], 'true'))
+            - task: Bash@3
+              displayName: Patch Coverage Results
+              inputs:
+                targetType: 'inline'
+                workingDirectory: ${{ parameters.buildDirectory }}/nyc/report
+                script: |
+                  sed -e 's/\(filename=\".*[\\/]external .*\)"\(.*\)""/\1\&quot;\2\&quot;"/' cobertura-coverage.xml > cobertura-coverage-patched.xml
+              condition: and(succeededOrFailed(), eq(variables['ReportDirExists'], 'true'))
+            - task: PublishCodeCoverageResults@1
+              displayName: Publish Code Coverage
+              inputs:
+                codeCoverageTool: Cobertura
+                summaryFileLocation: ${{ parameters.buildDirectory }}/nyc/report/cobertura-coverage-patched.xml
+                reportDirectory: ${{ parameters.buildDirectory }}/nyc/report
+                failIfCoverageEmpty: true
+              condition: and(succeededOrFailed(), eq(variables['ReportDirExists'], 'true'))
+
+          # Test - Upload results
+          - task: PublishTestResults@2
+            displayName: Publish Test Results
+            inputs:
+              testResultsFormat: 'JUnit'
+              testResultsFiles: '**/*junit-report.xml'
+              searchFolder: ${{ parameters.buildDirectory }}/nyc
+              mergeTestResults: false
+            condition: and(succeededOrFailed(), eq(variables['startTest'], 'true'))
+
+          # Test - Display failed tests
+          - task: CmdLine@2
+            displayName: Display Failed Tests
+            inputs:
+              script: node testReport.mjs ${{ parameters.buildDirectory }}/nyc/*junit-report.xml
+              workingDirectory: tools/pipelines/helper
+
+  # Publish stage
+  - ${{ if eq(variables.publish, true) }}:
+    - template: include-publish-npm-package.yml
       parameters:
-        poolBuild: Small
-        testPackage: "@fluidframework/azure-end-to-end-tests"
-        testWorkspace: ${{ variables.testWorkspace }}
-        testCommand: test:realsvc:tinylicious
-        extraDependencies: "cross-env mocha start-server-and-test @fluidframework/test-client-utils"
-        downloadAzureTestArtifacts: true
-        env:
-          FLUID_TEST_LOGGER_PKG_PATH: ${{ variables.testWorkspace }}/node_modules/@ff-internal/aria-logger # Contains getTestLogger impl to inject
+        namespace: ${{ parameters.namespace }}
+        tagName: ${{ parameters.tagName }}
+        publishNonScopedPackages: ${{ variables.publishNonScopedPackages }}
