Add parameter display task

diff --git a/tools/pipelines/test-reliability.yml b/tools/pipelines/test-reliability.yml
--- a/tools/pipelines/test-reliability.yml
+++ b/tools/pipelines/test-reliability.yml
@@ -21,11 +21,6 @@ parameters:
   - Test 3
   - Test 4
   - Test 5
-  - Test 6
-  - Test 7
-  - Test 8
-  - Test 9
-  - Test 10
 
 - name: buildDirectory
   type: string
@@ -135,7 +130,7 @@ stages:
         displayName: Build
         pool: ${{ parameters.poolBuild }}
         variables:
-          testCoverage: ${{ ne(variables['Build.Reason'], 'PullRequest') }}
+          testCoverage: true
           releaseBuildVar: $[variables.releaseBuild]
         steps:
         # Setup
@@ -143,6 +138,77 @@ stages:
           clean: true
           lfs: ${{ parameters.checkoutSubmodules }}
           submodules: ${{ parameters.checkoutSubmodules }}
+
+        - task: Bash@3
+          displayName: Parameters
+          inputs:
+            targetType: 'inline'
+            workingDirectory: ${{ parameters.buildDirectory }}
+            script: |
+              # Show all task group conditions
+
+              echo "
+              Pipeline Variables:
+                releaseBuild=$(releaseBuildVar)
+
+              Override Parameters:
+                publishOverride=${{ parameters.publishOverride }}
+                releaseBuildOverride=${{ parameters.releaseBuildOverride }}
+
+              Tasks Parameters:
+                BuildDir=${{ parameters.buildDirectory }}
+                Build=${{ parameters.taskBuild }}
+                Lint=${{ parameters.taskLint }}
+                Test=${{ convertToJson(parameters.taskTest) }}
+                BuildDoc=${{ parameters.taskBuildDocs }}
+                TestCoverage=$(testCoverage)
+
+              Publish Parameters:
+                nonScopedPackages=${{ join(', ', parameters.nonScopedPackages) }}
+
+              Computed variables:
+                shouldPublish=${{ variables.shouldPublish }}
+                componentDetection=${{ variables.componentDetection }}
+                publish=${{ variables.publish }}
+                canRelease=${{ variables.canRelease }}
+                publishNonScopedPackages=${{ variables.publishNonScopedPackages }}
+                targetBranchName = $(System.PullRequest.TargetBranch)
+
+                release=$(release)"
+
+              # Error checking
+              if [[ "$(release)" == "release" ]]; then
+                if [[ "${{ variables.canRelease }}" == "False" ]]; then
+                  echo "##vso[task.logissue type=error]Invalid branch ${{ variables['Build.SourceBranch'] }} for release"
+                  exit -1;
+                fi
+
+                if [ -f "lerna.json" ]; then
+                  grep -e fluid.*[0-9]-[0-9] `find packages -name 'package.json'`
+                else
+                  grep -e fluid.*[0-9]-[0-9] `find . -name 'package.json'`
+                fi
+
+                if [[ $? == 0 ]]; then
+                  echo "##vso[task.logissue type=error]Release shouldn't contain prerelease dependencies"
+                  exit -1;
+                fi
+              fi
+
+              if [[ "$(release)" == "prerelease" ]]; then
+                if [[ "${{ parameters.buildNumberInPatch }}" == "true" ]]; then
+                  echo "##vso[task.logissue type=error] Prerelease not allow for builds that put build number as the patch version"
+                  exit -1;
+                fi
+              fi
+
+              if [[ "$(release)" != "none" ]] && [[ "$(release)" != "" ]]; then
+                if [[ "${{ variables.publish }}" != "True" ]]; then
+                  echo "##vso[task.logissue type=error]'$(release)'' is set but package is not published. Either the branch doesn't default to publish or it is skipped."
+                  exit -1;
+                fi
+              fi
+
         # Install
         - task: UseNode@1
           displayName: Use Node 14.x
@@ -222,7 +288,7 @@ stages:
             # Some webpacked file using externals introduce file name with quotes in them
             # and Istanbul's cobertura reporter doesn't escape them causing parse error when we publish
             # A quick fix to patch the file with sed. (See https://github.com/bcoe/c8/issues/302)
-            - ${{ if eq(variables['testCoverage'], true) }}:
+            - ${{ if eq(true, true) }}:
               - task: Bash@3
                 displayName: 'Check for nyc/report directory'
                 inputs:
